[[flavour]]
name = 'arm64'
[flavour.defs]
is_default = true
[flavour.description]
hardware = '64-bit ARMv8 machines'

[[featureset]]
name = 'none'

[build]
compiler_gnutype_compat = 'arm-linux-gnueabihf'
enable_dtb = true
enable_rust = true
enable_signed = false
kernel_file = 'arch/arm64/boot/Image'
kernel_stem = 'vmlinuz'

[relations.image]
breaks = [
  'u-boot-efi-dtb (<< 5~)',
  'reform-tools (<< 1.83~)',
  'flash-kernel (<< 3.110~)',
]
